[package]
name = "rspec"
description = "Write Rspec-like tests with stable rust"
version = "1.0.0-beta.3"
authors = ["Thomas Wickham <mackwic@gmail.com>"]
license = "MPL-2.0"
homepage = "https://mackwic.github.io/rspec"
repository = "https://github.com/mackwic/rspec"
readme = "README.md"
keywords = ["rspec", "test", "harness", "bdd"]

[dependencies]
clippy = {version = "0.0", optional = true}
colored = "1.4.0"

[features]
default = []
